/* ════════════════════════════════════════════════════════
   MeetingMind — gemini-ws.js
   WebSocket connection lifecycle for the Gemini Live API.

   Responsibilities:
   - Connect / disconnect / reconnect with exponential backoff
   - Send the BidiGenerateContentSetup message
   - Route incoming messages to registered callbacks
   - Send audio chunks and text analysis requests
   - Handle Tool Calls (update_hud) and send ToolResponses

   Architecture:
   - The model is forced into "Tool-Only" mode via system prompt.
   - All structured output arrives via toolCall messages (pure JSON).
   - No audio is ever generated by the model, saving latency + tokens.
   ════════════════════════════════════════════════════════ */

import {
  GEMINI_MODEL, WS_BASE_URL, VOICE_NAME, AUDIO_MIME,
  SYSTEM_PROMPT, TOOL_DECLARATIONS,
  MAX_RECONNECT_ATTEMPTS, RECONNECT_BASE_DELAY_MS
} from './config.js';

// ── Connection state ──────────────────────────────────────────────────────
/** @type {WebSocket|null} */
let ws = null;
let isReady = false;
let reconnectAttempts = 0;

/** @type {string} API key set via init() */
let apiKey = '';

/** @type {boolean} Should we attempt reconnection on close? */
let shouldReconnect = false;

// ── Callbacks (set by the orchestrator) ───────────────────────────────────
/** @type {Record<string, Function>} */
const callbacks = {
  onSetupComplete:      () => {},
  onInputTranscription: (/** @type {string} */ _text) => {},
  onOutputTranscription:(/** @type {string} */ _text) => {},
  onModelText:          (/** @type {string} */ _text) => {},
  onToolCall:           (/** @type {object} */ _args) => {},
  onTurnComplete:       () => {},
  onInterrupted:        () => {},
  onError:              (/** @type {string} */ _msg) => {},
  onStatusChange:       (/** @type {string} */ _status) => {},
};

// ── Public API ────────────────────────────────────────────────────────────

/**
 * Initialize the module with the API key and event callbacks.
 * @param {string} key - Gemini API key
 * @param {Partial<typeof callbacks>} handlers - Event handlers
 */
export function init(key, handlers) {
  apiKey = key;
  Object.assign(callbacks, handlers);
}

/**
 * Update the API key (e.g. after user changes it in settings).
 * @param {string} key
 */
export function setApiKey(key) {
  apiKey = key;
}

/** @returns {boolean} Whether the WebSocket session is ready for data */
export function ready() {
  return isReady;
}

/**
 * Open a WebSocket connection and send the session setup message.
 * Audio capture should start AFTER onSetupComplete fires.
 */
export function connect() {
  if (ws && (ws.readyState === WebSocket.OPEN || ws.readyState === WebSocket.CONNECTING)) {
    return;
  }

  const url = `${WS_BASE_URL}?key=${apiKey}`;
  console.log('[GeminiWS] Connecting to:', url.replace(apiKey, '***'));

  ws = new WebSocket(url);
  isReady = false;
  shouldReconnect = true;
  callbacks.onStatusChange('connecting');

  ws.onopen = handleOpen;
  ws.onmessage = handleMessage;
  ws.onerror = handleError;
  ws.onclose = handleClose;
}

/**
 * Cleanly disconnect. Suppresses automatic reconnection.
 */
export function disconnect() {
  shouldReconnect = false;
  if (ws) {
    ws.onclose = null; // prevent reconnect logic
    ws.close();
    ws = null;
  }
  isReady = false;
  reconnectAttempts = 0;
  callbacks.onStatusChange('disconnected');
}

/**
 * Send a base64-encoded PCM audio chunk.
 * This is the HOT PATH — called ~4 times/second during recording.
 * No abstraction, no queuing, no batching. Straight to the wire.
 *
 * @param {string} base64Pcm - Base64-encoded Int16 PCM audio
 */
export function sendAudio(base64Pcm) {
  if (!isReady || !ws || ws.readyState !== WebSocket.OPEN) return;
  ws.send(JSON.stringify({
    realtimeInput: {
      audio: { data: base64Pcm, mimeType: AUDIO_MIME }
    }
  }));
}

/**
 * Request an AI analysis of the accumulated transcript.
 * Sends a clientContent text turn. The model should respond
 * exclusively via the update_hud tool call (no audio generated).
 *
 * @param {string} transcript - The full meeting transcript so far
 */
export function requestAnalysis(transcript) {
  if (!isReady || !ws || ws.readyState !== WebSocket.OPEN) return;
  ws.send(JSON.stringify({
    clientContent: {
      turns: [{
        role: 'user',
        parts: [{
          text: `Analyze this meeting transcript now. Call the update_hud function with your analysis. Do NOT speak.\n\nTranscript:\n${transcript}`
        }]
      }],
      turnComplete: true
    }
  }));
  console.log('[GeminiWS] Analysis requested (via tool call)');
}

// ── Internal handlers ─────────────────────────────────────────────────────

function handleOpen() {
  console.log('[GeminiWS] ✓ Connected');
  reconnectAttempts = 0;

  const setupMsg = {
    setup: {
      model: `models/${GEMINI_MODEL}`,
      generationConfig: {
        responseModalities: ['AUDIO'],
        speechConfig: {
          voiceConfig: {
            prebuiltVoiceConfig: { voiceName: VOICE_NAME }
          }
        }
      },
      systemInstruction: {
        parts: [{ text: SYSTEM_PROMPT }]
      },
      tools: TOOL_DECLARATIONS,
      inputAudioTranscription: {},
      outputAudioTranscription: {}
    }
  };

  console.log('[GeminiWS] → Setup sent (tool-only mode)');
  ws.send(JSON.stringify(setupMsg));
}

/** @param {MessageEvent} event */
async function handleMessage(event) {
  // Parse — handles Blob, ArrayBuffer, and string payloads
  let raw;
  if (event.data instanceof Blob) {
    raw = await event.data.text();
  } else if (event.data instanceof ArrayBuffer) {
    raw = new TextDecoder().decode(event.data);
  } else {
    raw = event.data;
  }

  let msg;
  try {
    msg = JSON.parse(raw);
  } catch {
    console.error('[GeminiWS] Unparseable message:', raw?.substring(0, 200));
    return;
  }

  // ── Route by message type ────────────────────────────────
  if (msg.setupComplete) {
    console.log('[GeminiWS] ✓ Session active (tool-only mode)');
    isReady = true;
    callbacks.onStatusChange('connected');
    callbacks.onSetupComplete();
    return;
  }

  if (msg.error) {
    console.error('[GeminiWS] Server error:', JSON.stringify(msg.error));
    callbacks.onError(msg.error.message || JSON.stringify(msg.error));
    return;
  }

  // Transcriptions (check both locations for API version compat)
  const inputT = msg.serverContent?.inputTranscription || msg.inputTranscription;
  if (inputT?.text) {
    callbacks.onInputTranscription(inputT.text);
  }

  const outputT = msg.serverContent?.outputTranscription || msg.outputTranscription;
  if (outputT?.text) {
    callbacks.onOutputTranscription(outputT.text);
  }

  // Model turn content (fallback — model should NOT generate audio/text
  // if tool-only mode is working correctly)
  if (msg.serverContent) {
    const sc = msg.serverContent;

    if (sc.modelTurn?.parts) {
      for (const part of sc.modelTurn.parts) {
        if (part.text) {
          callbacks.onModelText(part.text);
        }
        // part.inlineData (audio) is intentionally ignored
      }
    }

    if (sc.turnComplete) callbacks.onTurnComplete();
    if (sc.interrupted)  callbacks.onInterrupted();
  }

  // ── Tool Calls — the PRIMARY output path ─────────────────
  if (msg.toolCall) {
    handleToolCall(msg.toolCall);
  }
}

/**
 * Handle a BidiGenerateContentToolCall message.
 * Extracts the update_hud args, fires the callback, and sends
 * a ToolResponse back to the server to complete the round-trip.
 *
 * @param {object} toolCall - The toolCall payload from the server
 */
function handleToolCall(toolCall) {
  if (!toolCall.functionCalls || toolCall.functionCalls.length === 0) {
    console.warn('[GeminiWS] Empty toolCall received');
    return;
  }

  const functionResponses = [];

  for (const fc of toolCall.functionCalls) {
    console.log(`[GeminiWS] ⚡ Tool call: ${fc.name}`, fc.args);

    if (fc.name === 'update_hud') {
      // Fire the callback with the structured args
      callbacks.onToolCall({
        summary:     fc.args?.summary      || '',
        actionItems: fc.args?.action_items || [],
        decisions:   fc.args?.decisions    || [],
      });
    } else {
      console.warn(`[GeminiWS] Unknown tool: ${fc.name}`);
    }

    // Always respond to acknowledge the tool call
    functionResponses.push({
      name: fc.name,
      id: fc.id,
      response: { result: { status: 'success' } }
    });
  }

  // Send the ToolResponse back to the server
  if (ws && ws.readyState === WebSocket.OPEN) {
    ws.send(JSON.stringify({
      toolResponse: {
        functionResponses
      }
    }));
    console.log('[GeminiWS] → ToolResponse sent');
  }
}

/** @param {Event} err */
function handleError(err) {
  console.error('[GeminiWS] ✗ Error:', err);
  callbacks.onError('WebSocket connection error');
}

/** @param {CloseEvent} event */
function handleClose(event) {
  const reasons = {
    1000: 'Normal closure',
    1006: 'Abnormal closure',
    1011: 'Server error (check setup message)',
    4000: 'Invalid API key',
    4001: 'Model not found',
  };
  const reason = reasons[event.code] || event.reason || `Code ${event.code}`;
  console.error(`[GeminiWS] ✗ Closed — ${reason}`);

  isReady = false;
  callbacks.onStatusChange('disconnected');
  callbacks.onError(`Connection closed: ${reason}`);

  if (shouldReconnect && reconnectAttempts < MAX_RECONNECT_ATTEMPTS) {
    reconnectAttempts++;
    const delay = RECONNECT_BASE_DELAY_MS * Math.pow(2, reconnectAttempts - 1);
    console.log(`[GeminiWS] Reconnecting in ${delay}ms (${reconnectAttempts}/${MAX_RECONNECT_ATTEMPTS})`);
    callbacks.onStatusChange('reconnecting');
    setTimeout(() => { if (shouldReconnect) connect(); }, delay);
  } else if (reconnectAttempts >= MAX_RECONNECT_ATTEMPTS) {
    callbacks.onError('Max reconnect attempts reached. Click Start to retry.');
  }
}
